name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"   # Every 6 hours
  workflow_dispatch:        # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake grids
        uses: Platane/snk@v3
        with:
          github_user_name: tanaytr
          outputs: |
            output/github-contribution-grid-snake-dark.svg
            output/github-contribution-grid-snake.svg

      - name: Push snake to output-branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
          fqdn: github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
